# Generated by Django 6.0.2 on 2026-04-26 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_1_identidad_relaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosIncidentes',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('creado_por', models.CharField(blank=True, default='', max_length=128)),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=128)),
                ('tipo_evento', models.CharField(choices=[('Caída', 'Caída'), ('Emergencia Médica', 'Emergencia Médica'), ('Conflicto', 'Conflicto'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('acciones_tomadas', models.TextField(blank=True)),
                ('gravedad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10)),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1_identidad_relaciones.pacientemodel')),
            ],
            options={
                'db_table': 'tb_eventos_incidentes',
                'ordering': ['-fecha_evento', '-hora_evento'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinicaUnificada',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_ingreso', models.TextField(blank=True)),
                ('diagnostico_inicial', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('tratamiento_actual', models.TextField(blank=True)),
                ('nutricion_asignada', models.TextField(blank=True)),
                ('creado_por', models.CharField(blank=True, default='', max_length=128)),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=128)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_1_identidad_relaciones.pacientemodel')),
            ],
            options={
                'db_table': 'tb_historia_clinica_unificada',
            },
        ),
    ]
