# Generated by Django 6.0.3 on 2026-03-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliarModel',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_dni', models.ImageField(blank=True, null=True, upload_to='familiares/dni/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
                'db_table': 'tb_familiar',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PacienteModel',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/')),
                ('imagen_dni', models.ImageField(blank=True, null=True, upload_to='pacientes/dni/')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero'), ('SOLTERA', 'Soltera'), ('CASADO', 'Casado'), ('CASADA', 'Casada'), ('DIVORCIADO', 'Divorciado'), ('DIVORCIADA', 'Divorciada'), ('VIUDO', 'Viudo'), ('VIUDA', 'Viuda')], max_length=15, null=True)),
                ('estado_paciente', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('ACTIVO', 'Activo'), ('HOSPITALIZADO', 'Hospitalizado'), ('EN_TRATAMIENTO', 'En tratamiento'), ('ALTA_MEDICA', 'Alta médica'), ('REFERIDO', 'Referido'), ('FALLECIDO', 'Fallecido'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'tb_paciente',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RelacionPacienteFamiliarModel',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HIJO', 'Hijo'), ('HIJA', 'Hija'), ('CONYUGE', 'Cónyuge'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('ABUELO', 'Abuelo'), ('ABUELA', 'Abuela'), ('NIETO', 'Nieto'), ('NIETA', 'Nieta'), ('TIO', 'Tío'), ('TIA', 'Tía'), ('SOBRINO', 'Sobrino'), ('SOBRINA', 'Sobrina'), ('PRIMO', 'Primo'), ('PRIMA', 'Prima'), ('OTRO', 'Otro')], max_length=20)),
                ('es_responsable_emergencia', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_pacientes', to='app_1_identidad_relaciones.familiarmodel')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_familiares', to='app_1_identidad_relaciones.pacientemodel')),
            ],
            options={
                'db_table': 'tb_relacion_paciente_familiar',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
