# Generated by Django 6.0.4 on 2026-05-10 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_1_identidad_relaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicacionPaciente',
            fields=[
                ('id_medicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Pastilla', 'Pastilla'), ('Capsula', 'Cápsula'), ('Tableta', 'Tableta'), ('Comprimido', 'Comprimido'), ('Jarabe', 'Jarabe'), ('Suspension', 'Suspensión'), ('Solucion_Oral', 'Solución Oral'), ('Gotas_Orales', 'Gotas Orales'), ('Inyectable', 'Inyectable'), ('Ampolla', 'Ampolla'), ('Vial', 'Vial'), ('Suero', 'Suero'), ('Crema', 'Crema'), ('Pomada', 'Pomada'), ('Gel', 'Gel'), ('Parche', 'Parche'), ('Supositorio', 'Supositorio'), ('Ovulo', 'Óvulo'), ('Inhalador', 'Inhalador'), ('Nebulizacion', 'Nebulización'), ('Colirio', 'Colirio'), ('Gotas_Oticas', 'Gotas Óticas'), ('Spray_Nasal', 'Spray Nasal'), ('Polvo', 'Polvo'), ('Sobres', 'Sobres')], max_length=20)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('via_administracion', models.CharField(choices=[('Oral', 'Oral'), ('Topica', 'Topica'), ('IV', 'IV')], max_length=20)),
                ('horarios_aplicacion', models.CharField(max_length=200)),
                ('duracion_dias', models.PositiveIntegerField()),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('proveedor_o_familiar', models.CharField(max_length=150)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones_paciente', to='app_1_identidad_relaciones.pacientemodel')),
            ],
            options={
                'verbose_name': 'Medicacion de Paciente',
                'verbose_name_plural': 'Medicaciones de Pacientes',
                'db_table': 'tb_medicacion_paciente',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='AdministracionMedicacion',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_programada', models.DateTimeField()),
                ('fecha_hora_real', models.DateTimeField(blank=True, null=True)),
                ('cantidad_administrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Rechazado', 'Rechazado'), ('Omitido', 'Omitido')], default='Entregado', max_length=15)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('id_personal_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administraciones_medicacion', to=settings.AUTH_USER_MODEL)),
                ('id_medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administraciones', to='app_3_medicacion_inventario.medicacionpaciente')),
            ],
            options={
                'verbose_name': 'Administracion de Medicacion',
                'verbose_name_plural': 'Administraciones de Medicacion',
                'db_table': 'tb_administracion_medicacion',
                'ordering': ['-fecha_hora_programada'],
            },
        ),
        migrations.CreateModel(
            name='RecetasPaciente',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('medico_prescriptor', models.CharField(max_length=150)),
                ('fecha_prescripcion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('diagnostico_receta', models.TextField()),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Vencida', 'Vencida'), ('Suspendida', 'Suspendida')], default='Activa', max_length=15)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_paciente', to='app_1_identidad_relaciones.pacientemodel')),
            ],
            options={
                'verbose_name': 'Receta de Paciente',
                'verbose_name_plural': 'Recetas de Pacientes',
                'db_table': 'tb_recetas_paciente',
                'ordering': ['-fecha_prescripcion'],
            },
        ),
        migrations.AddField(
            model_name='medicacionpaciente',
            name='id_receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicaciones', to='app_3_medicacion_inventario.recetaspaciente'),
        ),
    ]
