# Generated by Django 6.0.2 on 2026-05-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3_medicacion_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracionmedicacion',
            name='id_personal_entrega',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
