# Generated by Django 6.0.2 on 2026-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_3_medicacion_inventario', '0002_alter_administracionmedicacion_id_personal_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='administracionmedicacion',
            name='nombre_personal_entrega',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
